post_install() {
  _rmsymlink
  _mksymlink
}

post_upgrade() {
  post_install
}

post_remove() {
  _rmsymlink
}

_mksymlink() {
  echo -n "Symlinking executables... "
    for _bin in bootstrap.js casperjs; do
      ln -s /usr/share/casperjs/bin/$_bin /usr/bin/$_bin
    done
  echo "done"
}

_rmsymlink() {
  echo -n "Removing symlinks... "
    for _bin in bootstrap.js casperjs; do
      rm -f /usr/bin/$_bin
    done
  echo "done"
}
