post_install() {
  printf "$fuzzy\n"
}

read -d '' fuzzy <<'EOF'
Optional fzf key bindings have been placed here:

    /etc/profile.d/fzf.sh

To utilize, add the following to your bash config:

    . /etc/profile.d/fzf.sh

Or for zsh, add the following to your config:

    . /etc/profile.d/fzf.zsh

Or for fish, add the following to your config:

    . /etc/profile.d/fzf.fish

For fish, key bindings are in:

    /usr/share/fish/functions/fzf_key_bindings.fish
EOF
