--- ./Makefile	2013-09-30 17:29:12.323228849 -0700
+++ ./Makefile	2013-09-30 17:31:57.603224531 -0700
@@ -53,30 +53,30 @@
 install: all
 # install rs-esrve
 	@echo "[INSTALL] rs-serve"
-	@install -s rs-serve /usr/bin
+	@install -s rs-serve $(DESTDIR)/usr/bin
 # install tools
 	@echo "[INSTALL] rs-list-tokens"
-	@install -s tools/list-tokens /usr/bin/rs-list-tokens
+	@install -s tools/list-tokens $(DESTDIR)/usr/bin/rs-list-tokens
 	@echo "[INSTALL] rs-lookup-token"
-	@install -s tools/lookup-token /usr/bin/rs-lookup-token
+	@install -s tools/lookup-token $(DESTDIR)/usr/bin/rs-lookup-token
 	@echo "[INSTALL] rs-add-token"
-	@install -s tools/add-token /usr/bin/rs-add-token
+	@install -s tools/add-token $(DESTDIR)/usr/bin/rs-add-token
 	@echo "[INSTALL] rs-remove-token"
-	@install -s tools/remove-token /usr/bin/rs-remove-token
+	@install -s tools/remove-token $(DESTDIR)/usr/bin/rs-remove-token
 # create working dir
 	@echo "[MKDIR] /var/lib/rs-serve/"
-	@mkdir -p /var/lib/rs-serve
+	@mkdir -p $(DESTDIR)/var/lib/rs-serve
 # create 'authorizations' dir (root of the BDB environment used to store authorization tokens)
 	@echo "[MKDIR] /var/lib/rs-serve/authorizations/"
-	@mkdir /var/lib/rs-serve/authorizations
+	@mkdir -p $(DESTDIR)/var/lib/rs-serve/authorizations
 # install init script
 	@echo "[INSTALL] /etc/init.d/rs-serve"
-	@install -m 0755 init-script.sh /etc/init.d/rs-serve
+	@install -m 0755 init-script.sh $(DESTDIR)/etc/init.d/rs-serve
 ifeq (${shell test -f /etc/default/rs-serve >/dev/null 2>&1 ; echo $$?}, 0)
 	@echo "[EXISTS] /etc/default/rs-serve"
 else
 	@echo "[INSTALL] /etc/default/rs-serve"
-	@install init-script-defaults /etc/default/rs-serve
+	@install init-script-defaults $(DESTDIR)/etc/default/rs-serve
 endif
 ifeq (${shell type update-rc.d >/dev/null 2>&1 ; echo $$?}, 0)
 	@echo "[UPDATE-RC.D]"
