--- ./src/Makefile	2013-07-21 20:10:10.575244408 -0700
+++ ./src/Makefile	2013-07-21 20:10:55.261912431 -0700
@@ -11,11 +11,13 @@
 INCLUDEPATHS= \
 	-I../libs/openssl-1.0.1e/include \
 	-I../libs/db-4.7.25.NC/build_unix \
+	-I/usr/lib \
 	-I../libs/boost_1_50_0
 
 LIBPATHS= \
 	-L../libs/openssl-1.0.1e \
 	-L../libs/db-4.7.25.NC/build_unix \
+	-L/usr/lib/libboost_filesystem.so \
 	-L../libs/boost_1_50_0/stage/lib
 
 LIBBOOST_SUFFIX=
